services:

  web-search:
    image: muka/web-search-mcp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3006:3006
    environment:
      - SERPER_API_KEY=your key
      - PORT=3006
